# Generated by Django 3.2.5 on 2021-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('성함', models.TextField(default='')),
                ('연락처', models.TextField(default='')),
                ('희망픽업일시간', models.TextField(default='')),
                ('맛', models.CharField(choices=[('CHO', '초콜릿'), ('STR', '딸기'), ('VAN', '바닐라'), ('RED', '레드벨벳')], default='CHO', max_length=4)),
            ],
        ),
    ]
