# Generated by Django 3.2.5 on 2021-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakecollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='희망픽업일시간',
        ),
        migrations.AddField(
            model_name='content',
            name='희망픽업시간',
            field=models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], default='10:00', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='희망픽업일',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='맛',
            field=models.CharField(choices=[('초콜릿', '초콜릿'), ('딸기', '딸기'), ('바닐라', '바닐라'), ('레드벨벳', '레드벨벳')], default='초콜릿', max_length=4),
        ),
        migrations.AlterField(
            model_name='content',
            name='성함',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='연락처',
            field=models.CharField(max_length=200),
        ),
    ]
