# Generated by Django 3.2.5 on 2021-07-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakecollection', '0004_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='image',
            new_name='원하시는도안사진첨부',
        ),
    ]
