# Generated by Django 3.2.5 on 2021-07-02 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakecollection', '0005_rename_image_content_원하시는도안사진첨부'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='datefield',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
